[package]
name = "cookie_check"
version = "0.1.0"
authors = ["Liam P. White <byteslice@airmail.cc>"]

[dependencies]
base64 = "0.6.0"
openssl = "0.9.15"
percent-encoding = "1.0.0"
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
panic = "abort"
