[package]
name = "cookie_check"
version = "1.0.0"
authors = ["Liam P. White <byteslice@airmail.cc>"]
edition = "2024"

[dependencies]
base64 = "0.12"
ring = "0.17.14"

[lib]
crate-type = ["cdylib"]

[profile.dev]
panic = "abort"

[profile.release]
lto = true
# opt-level = "z"
panic = "abort"
